#!/usr/bin/env python3
"""
Generate supabase migration SQL from pool JSON files.
Output: supabase/migrations/20260306000001_pool_migration.sql
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
POOLS_DIR = os.path.join(ROOT, "frontend", "src", "data", "exam_pools")
OUT_FILE = os.path.join(ROOT, "supabase", "migrations", "20260306000001_pool_migration.sql")


def js(val) -> str:
    """Serialize a Python value to a PostgreSQL-safe JSON literal."""
    return "'" + json.dumps(val, ensure_ascii=False).replace("'", "''") + "'"


def sql_str(val) -> str:
    if val is None:
        return "NULL"
    return "'" + str(val).replace("'", "''") + "'"


def load(part: int):
    path = os.path.join(POOLS_DIR, f"p{part}_pool.json")
    with open(path) as f:
        return json.load(f)


lines = []
lines.append("-- Auto-generated pool migration — do not edit manually")
lines.append("-- Generated by scripts/toeic/generate_pool_migration.py")
lines.append("")

# 1. Make mock_exams.dataset_id nullable
lines.append("-- Make mock_exams.dataset_id nullable (new exams no longer use it)")
lines.append("ALTER TABLE mock_exams")
lines.append("  ALTER COLUMN dataset_id DROP NOT NULL,")
lines.append("  ALTER COLUMN dataset_id SET DEFAULT NULL;")
lines.append("")

# 2. Truncate all part tables
tables = [
    "toeic_listening_part1",
    "toeic_listening_part2",
    "toeic_listening_part3",
    "toeic_listening_part4",
    "toeic_reading_part5",
    "toeic_reading_part6",
    "toeic_reading_part7",
]
lines.append("-- Repopulate all pool tables")
lines.append(f"TRUNCATE {', '.join(tables)};")
lines.append("")

# ── Part 1 ────────────────────────────────────────────────────────────────────
p1 = load(1)
lines.append("-- Part 1 (24 questions)")
lines.append("INSERT INTO toeic_listening_part1")
lines.append("  (position, image, statements, answer, image_url, audio_urls, is_exam, dataset_id)")
lines.append("VALUES")
rows = []
for i, q in enumerate(p1):
    image = q.get("image") or ""
    statements = q.get("statements", [])
    answer = q["answer"]
    image_url = q.get("image_url")
    audio_urls = q.get("audio_urls")
    rows.append(
        f"  ({i+1}, {sql_str(image)}, {js(statements)}, {sql_str(answer)}, "
        f"{sql_str(image_url)}, {js(audio_urls) if audio_urls else 'NULL'}, true, NULL)"
    )
lines.append(",\n".join(rows) + ";")
lines.append("")

# ── Part 2 ────────────────────────────────────────────────────────────────────
p2 = load(2)
lines.append("-- Part 2 (100 questions)")
lines.append("INSERT INTO toeic_listening_part2")
lines.append("  (position, category, question, options, answer, question_audio_url, option_audio_urls, is_exam, dataset_id)")
lines.append("VALUES")
rows = []
for i, q in enumerate(p2):
    rows.append(
        f"  ({i+1}, {sql_str(q.get('category'))}, {sql_str(q['question'])}, "
        f"{js(q['options'])}, {sql_str(q['answer'])}, "
        f"{sql_str(q.get('question_audio_url'))}, "
        f"{js(q['option_audio_urls']) if q.get('option_audio_urls') else 'NULL'}, "
        f"true, NULL)"
    )
lines.append(",\n".join(rows) + ";")
lines.append("")

# ── Part 3 ────────────────────────────────────────────────────────────────────
p3 = load(3)
lines.append("-- Part 3 (52 conversations)")
lines.append("INSERT INTO toeic_listening_part3")
lines.append("  (position, dialogue, questions, audio_url, is_exam, dataset_id)")
lines.append("VALUES")
rows = []
for i, q in enumerate(p3):
    rows.append(
        f"  ({i+1}, {js(q['dialogue'])}, {js(q['questions'])}, "
        f"{sql_str(q.get('audio_url'))}, true, NULL)"
    )
lines.append(",\n".join(rows) + ";")
lines.append("")

# ── Part 4 ────────────────────────────────────────────────────────────────────
p4 = load(4)
lines.append("-- Part 4 (40 talks)")
lines.append("INSERT INTO toeic_listening_part4")
lines.append("  (position, title, text, questions, audio_url, is_exam, dataset_id)")
lines.append("VALUES")
rows = []
for i, q in enumerate(p4):
    rows.append(
        f"  ({i+1}, {sql_str(q.get('title'))}, {sql_str(q['text'])}, "
        f"{js(q['questions'])}, {sql_str(q.get('audio_url'))}, true, NULL)"
    )
lines.append(",\n".join(rows) + ";")
lines.append("")

# ── Part 5 ────────────────────────────────────────────────────────────────────
p5 = load(5)
lines.append("-- Part 5 (120 questions)")
lines.append("INSERT INTO toeic_reading_part5")
lines.append("  (position, text, options, answer, is_exam, dataset_id)")
lines.append("VALUES")
rows = []
for i, q in enumerate(p5):
    rows.append(
        f"  ({i+1}, {sql_str(q['text'])}, {js(q['options'])}, "
        f"{sql_str(q['answer'])}, true, NULL)"
    )
lines.append(",\n".join(rows) + ";")
lines.append("")

# ── Part 6 ────────────────────────────────────────────────────────────────────
p6 = load(6)
lines.append("-- Part 6 (16 passages)")
lines.append("INSERT INTO toeic_reading_part6")
lines.append("  (position, doctype, text, questions, is_exam, dataset_id)")
lines.append("VALUES")
rows = []
for i, q in enumerate(p6):
    rows.append(
        f"  ({i+1}, {sql_str(q.get('doctype'))}, {sql_str(q['text'])}, "
        f"{js(q['questions'])}, true, NULL)"
    )
lines.append(",\n".join(rows) + ";")
lines.append("")

# ── Part 7 ────────────────────────────────────────────────────────────────────
p7 = load(7)
lines.append("-- Part 7 (57 passages)")
lines.append("INSERT INTO toeic_reading_part7")
lines.append("  (position, documents, questions, is_exam, dataset_id)")
lines.append("VALUES")
rows = []
for i, q in enumerate(p7):
    rows.append(
        f"  ({i+1}, {js(q['documents'])}, {js(q['questions'])}, true, NULL)"
    )
lines.append(",\n".join(rows) + ";")
lines.append("")

sql = "\n".join(lines)
os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)
with open(OUT_FILE, "w") as f:
    f.write(sql)

total_lines = sql.count("\n")
print(f"Written: {OUT_FILE}")
print(f"Lines: {total_lines}")
print(f"Size: {len(sql):,} bytes")
